source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sqlite3'

gem 'sass-rails', github: 'arpancj/sass-rails', ref: 'b6eb2f944f05f28e734ff4b118195d591175c952' # sass 3.3.x
gem 'uglifier', '~> 2.5.1'
gem 'coffee-rails', '~> 4.0.1'
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
#gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

# gem 'rails-disco', '~> 0.5.2'
gem 'active_event', path: 'D:/arB/projects/eventsource/rails-disco/active_event'
gem 'active_projection', path: 'D:/arB/projects/eventsource/rails-disco/active_projection'
gem 'active_domain', path: 'D:/arB/projects/eventsource/rails-disco/active_domain'
gem 'disco-railties', path: 'D:/arB/projects/eventsource/rails-disco/disco-railties'
gem 'rails-disco', path: 'D:/arB/projects/eventsource/rails-disco'

# gem 'react-rails', '~> 1.0.0'
gem 'sprockets-coffee-react'
gem 'react-rails', github: 'arBmind/react-rails', branch: 'master'

gem 'puma'

gem 'tzinfo-data', platforms: [:mingw, :mswin]

group :development, :nitrous do
  # improve error screen
  gem 'better_errors'
  gem 'binding_of_caller'
  # gem 'meta_request' -- using both fails

  # suppress noisy asset pipeline
  gem 'quiet_assets'

  gem 'coffee-rails-source-maps', '~> 1.4.0'
  gem 'sass-rails-source-maps', '~> 0.0.4'
end
